import { Product } from '../../../../../interfaces/Product'

const getImagePath = (id: number): string => `src/assets/Coffes/Coffee${id}.svg`
export const products: Product[] = [
  {
    id: 1,
    image: getImagePath(1),
    typesCoffee: ['Tradicional', 'Com Leite'],
    title: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 2,
    image: getImagePath(2),
    typesCoffee: ['Tradicional'],
    title: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 3,
    image: getImagePath(3),
    typesCoffee: ['Tradicional'],
    title: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 4,
    image: getImagePath(4),
    typesCoffee: ['Tradicional', 'gelado'],
    title: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 5,
    image: getImagePath(5),
    typesCoffee: ['Tradicional', 'com leite'],
    title: 'Café com Leite',
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 6,
    image: getImagePath(6),
    typesCoffee: ['Tradicional', 'com leite'],
    title: 'Latte',
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 7,
    image: getImagePath(7),
    typesCoffee: ['Tradicional', 'com leite'],
    title: 'Capuccino',
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 8,
    image: getImagePath(8),
    typesCoffee: ['Tradicional', 'com leite'],
    title: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 9,
    image: getImagePath(9),
    typesCoffee: ['Tradicional', 'com leite'],
    title: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 10,
    image: getImagePath(10),
    typesCoffee: ['especial', 'com leite'],
    title: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 11,
    image: getImagePath(11),
    typesCoffee: ['especial', 'alcoólico', 'gelado'],
    title: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 12,
    image: getImagePath(12),
    typesCoffee: ['especial'],
    title: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 13,
    image: getImagePath(13),
    typesCoffee: ['especial'],
    title: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: '9.90',
    quantity: 1,
  },
  {
    id: 14,
    image: getImagePath(14),
    typesCoffee: ['especial', 'alcoólico'],
    title: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: '9.90',
    quantity: 1,
  },
]
